### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [grevelem/TC359project11#1]
It looks like there's one criterion that you forgot:

> NOT display any links to unauthorized actions to anonymous visitors (such as links to create a new record, edit a record, or delete a record)

Check out how we're only showing a link to sign out if a user is signed in and use the same technique to only show links to these actions when signed in.

**Comment by grevelem** [comment]
@chrisvfritz oops I think I must've misunderstood the directions. It should be good to go now, made the necessary changes so "show" is the only feature allowed on the basketball page when a user isn't signed in. Let me know if anything else needs to be addressed. Thank you!

**Comment by chrisvfritz** [comment]
Better, but the link to create a new basketball player in the `index` view and the edit link in the `show` view are still appearing when not signed in.

**Comment by grevelem** [comment]
@chrisvfritz Should be all set I think!

**Comment by chrisvfritz** [comment]
:+1: Excellent!
